import { type JsonObject, type QuackResult } from "../core/types.js";
import { type SkillAttribution } from "../cos/types.js";
import { type Task, type TaskStep } from "../runtime/task.js";
import { type ToolInvocation, type ToolInvocationExecutor } from "../tools/tool.js";
import { type ToolUse } from "./tool-interfaces.js";
import type { WorkflowState } from "../engine/types.js";

export interface BrainSkillSelection {
  readonly id: string;
  readonly contextKey: string;
  readonly contextTags: readonly string[];
  readonly selected: readonly SkillAttribution[];
  readonly reason: string;
  readonly confidence: number;
}

/**
 * BrainContext provides the context in which the brain operates.
 */
export interface BrainContext {
  readonly recoveryEvidence?: import("../contracts/v1/contracts.js").EvidenceRecordV1;
  readonly missionId?: string;
  readonly agentId?: string;
  readonly skillId?: string;
  readonly signal?: AbortSignal;
  readonly deadline?: string;
  readonly actor: string;
  readonly sessionId: string;
  readonly workspaceId: string;
  readonly executeTool?: ToolInvocationExecutor;
  readonly skillSelection?: BrainSkillSelection;
}

/**
 * A single step in a plan produced by the Planner.
 */
export interface PlanStep {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly estimatedComplexity: "low" | "medium" | "high";
  readonly dependencies: readonly string[]; // IDs of steps that must complete before this one
  readonly tools: readonly string[]; // Tool IDs that may be needed
  readonly toolInvocations?: readonly ToolInvocation[]; // Concrete, validated-at-runtime tool calls
}

/**
 * A complete plan generated by the Planner.
 */
export interface Plan {
  readonly goal: string;
  readonly steps: readonly PlanStep[];
  readonly strategy: string; // High-level approach description
  readonly estimatedTotalComplexity: "low" | "medium" | "high";
  readonly requiresPermissions: readonly string[];
}

/**
 * The result of executing a task through the brain.
 */
export interface ExecutionResult {
  readonly summary: string;
  readonly data: JsonObject;
  readonly toolCalls: readonly ToolUse[];
  readonly reflectionNotes: readonly string[];
  readonly metrics: ExecutionMetrics;
}

/**
 * Metrics collected during execution.
 */
export interface ExecutionMetrics {
  readonly planningTimeMs: number;
  readonly executionTimeMs: number;
  readonly totalSteps: number;
  readonly completedSteps: number;
  readonly failedSteps: number;
  readonly toolCallsMade: number;
  readonly tokenUsage?: JsonObject;
}

/**
 * Represents a reasoning/decision made by the Reasoner.
 */
export interface Reasoning {
  readonly question: string;
  readonly analysis: string;
  readonly conclusion: string;
  readonly confidence: number; // 0.0 to 1.0
  readonly alternativesConsidered: readonly string[];
  readonly reasoningChain: readonly string[];
}

/**
 * Reflection on an action or outcome.
 */
export interface Reflection {
  readonly targetId: string; // ID of the step/tool/action being reflected on
  readonly outcome: "success" | "failure" | "partial";
  readonly observations: readonly string[];
  readonly lessons: readonly string[];
  readonly recommendations: readonly string[];
  readonly shouldRetry: boolean;
  readonly retryApproach?: string;
}

/**
 * The Brain orchestrates planning, reasoning, execution, and reflection.
 * It is the central intelligence hub of QUACK.
 */
export interface Brain {
  readonly verifyExecution?: (task: Task, state: WorkflowState, context?: BrainContext) => Promise<{ readonly success: boolean; readonly reason: string }>;
  /**
   * Given a task, produce a detailed plan with steps, dependencies, and strategy.
   */
  plan(task: Task, context: BrainContext): Promise<QuackResult<Plan>>;

  /**
   * Execute a task according to its plan, using tools and providers as needed.
   */
  execute(task: Task, context: BrainContext): Promise<QuackResult<ExecutionResult>>;

  /**
   * Perform reasoning/decomposition on a complex question.
   */
  reason(question: string, context: BrainContext): Promise<QuackResult<Reasoning>>;

  /**
   * Reflect on a completed action or outcome.
   */
  reflect(targetId: string, outcome: unknown, context: BrainContext): Promise<QuackResult<Reflection>>;
}
